Takip.Web/Models/AccountEditModel.cs
namespace Takip.Web.Models
{
    public class AccountEditModel
    {

    }
}

Takip.Web/Models/ErrorViewModel.cs
namespace Takip.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Takip.Web/Models/LoginModel.cs
namespace Takip.Web.Models
{
    public class LoginModel
    {
        public string EMail { get; set; }
        public string Password { get; set; }
    }
}

Takip.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Takip.Web.Code.Filters;
using Takip.Web.Code.Rest;

namespace Takip.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            IndexRestClient client = new IndexRestClient();
            dynamic result1 = client.PersonnelCount();

            bool success1 = result1.success;
            if (success1)
                ViewBag.PersonnelCount = result1.data;

            dynamic result2 = client.ServiceCount();

            bool success2 = result2.success;
            if (success2)
                ViewBag.ServiceCount = result2.data;

            dynamic result3 = client.ProductCount();

            bool success3 = result3.success;
            if (success3)
                ViewBag.ProductCount = result3.data;

            dynamic result4 = client.CustomerCount();

            bool success4 = result4.success;
            if (success4)
                ViewBag.CustomerCount = result4.data;
            return View();
        }
        [AuthActionFilter(Role = "Admin")]
        public IActionResult Role() => View();
        [AuthActionFilter(Role = "Admin")]
        public IActionResult Category() => View();
        [AuthActionFilter]
        public IActionResult Customer() => View();
        [AuthActionFilter]
        public IActionResult Service() => View();
        [AuthActionFilter(Role = "Admin")]
        public IActionResult Product() => View();
        [AuthActionFilter(Role = "Admin")]
        public IActionResult Personnel() => View();

    }
}

Takip.Web/Areas/Admin/Controllers/PersonnelController.cs
using Microsoft.AspNetCore.Mvc;
using Takip.Web.Code.Rest;
using Takip.Web.Code;
using Takip.Web.Models;

namespace Takip.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PersonnelController : Controller
    {
        public IActionResult AccountDetails() => View();

        //public IActionResult Edit(AccountEditModel model)
        //{
        //    UserRestClient client = new UserRestClient();
        //    dynamic result = client.Login(model.EMail, model.Password);

        //    bool success = result.success;

        //    if (success)
        //    {
        //        Repo.Session.Email = model.EMail;
        //        Repo.Session.Name = (string)result.name;
        //        Repo.Session.Token = (string)result.data;
        //        Repo.Session.Role = (string)result.role;

        //        ViewBag.Detay = result.data;

        //        return RedirectToAction("Index", "Home", new { area = "Admin" });
        //    }
        //    else
        //    {
        //        ViewBag.LoginError = (string)result.message;
        //        return View("Login");
        //    }
        //}
    }
}

Takip.Web/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System.Reflection;
using Takip.Web.Code;
using Takip.Web.Code.Rest;
using Takip.Web.Models;

namespace Takip.Web.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login() => View();

        public IActionResult Unauthorized() => View();

        public IActionResult GirisYap(LoginModel model)
        {
            UserRestClient client = new UserRestClient();
            dynamic result = client.Login(model.EMail, model.Password);

            bool success = result.success;

            if (success)
            {
                Repo.Session.Email = model.EMail;
                Repo.Session.Name = (string)result.name;
                Repo.Session.Token = (string)result.data;
                Repo.Session.Role = (string)result.role;

                return RedirectToAction("Index", "Home", new { area = "Admin"});
            }
            else
            {
                ViewBag.LoginError = (string)result.message;
                return View("Login");
            }

            // View -> Controller -> UserRestClient -> RestCharp ile webapi'ye bağlanıyor -> Database
        }

        public IActionResult Logout()
        {
            Repo.Session.Email = "";
            Repo.Session.Name = "";
            Repo.Session.Token = "";
            Repo.Session.Role = "";

            return RedirectToAction("Login", "Account");
        }
    }
}

Takip.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Takip.Web.Models;
using Takip.Web.Code.Filters;

namespace Takip.Web.Controllers
{
    [AuthActionFilter]
    public class HomeController : Controller
    {

        public HomeController() { }

        public IActionResult Index() => RedirectToAction("Login", "Account");

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Takip.Web/Areas/Admin/Views/Home/Category.cshtml
<script type="text/javascript" src="~/js/admin/category.js" asp-append-version="true"></script>
<div class="row">
    <div class="p-3 col-12">
        <div>
            <div class="d-inline-flex mt-5 text-center">
                <div>
                    <label for="inputSearch1" class="form-label mt-3 me-3">Kategori Adına Göre</label>
                    <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch1" onkeyup='tableSearch(0,"inputSearch1","categoryTable")'>
                </div>
                <div>
                    <label for="inputSearch2" class="form-label mt-3 me-3">Üst Kategoriye Göre</label>
                    <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch2" onkeyup='tableSearch(1,"inputSearch2","categoryTable")'>
                </div>
            </div>
        </div>

        <div id="divCategories" class="mt-3">
        </div>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" onclick="NewCategory()">
            Yeni Kategori Ekle
        </button>

        <!-- Modal -->
        <div class="modal fade" id="categoryModal" tabindex="-1" aria-labelledby="categoryModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="categoryModalLabel">Kategori Bilgileri</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <label for="inputCategoryName" class="form-label">Kategori Adı</label>
                        <input type="text" id="inputCategoryName" class="form-control">

                        <label for="selectTopCategories" class="form-label">Üst Kategori</label>
                        <select type="text" id="selectTopCategories" class="form-control"></select>


                        <div class="form-check mt-2">
                            <input class="form-check-input checked" type="checkbox" value="" id="inputActive">
                            <label class="form-check-label" for="inputActive">
                                Aktif
                            </label>
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Vazgeç</button>
                        <button type="button" class="btn btn-primary" onclick="SaveCategory()">Kaydet</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Takip.Web/Areas/Admin/Views/Home/Customer.cshtml
<script type="text/javascript" src="~/js/admin/customer.js" asp-append-version="true"></script>
<div class="row">
<div class="p-3 col-12">
    <h2>Müşteriler</h2>

    
    <div>
        <div class="d-inline-flex mt-3 text-center">
            <div>
            <label for="inputSearch1" class="form-label mt-3 me-3">İsme Göre Ara</label>
                <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch1" onkeyup='tableSearch(0,"inputSearch1","customerTable")'>
            </div>
            <div>
                <label for="inputSearch2" class="form-label mt-3 me-3">Telefona Göre Ara</label>
                <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch2" onkeyup='tableSearch(1,"inputSearch2","customerTable")'>
            </div>
            <div>
                <label for="inputSearch3" class="form-label mt-3 me-3">Ev Telefonuna Göre Ara</label>
                <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch3" onkeyup='tableSearch(2,"inputSearch3","customerTable")'>
            </div>
            <div>
                <label for="inputSearch4" class="form-label mt-3 me-3">Ürüne Göre Ara</label>
                <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch4" onkeyup='tableSearch(3,"inputSearch4","customerTable")'>
            </div>

        </div>
    </div>
    <div id="divCustomers" class="font-size-medium mt-3">
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary mt-3" data-bs-toggle="modal" onclick="NewCustomer()">
        Yeni Müşteri Ekle
    </button>


    <!-- Address Modal -->
    <div class="modal modal-xl fade" id="addressesModal" tabindex="-1" aria-labelledby="addressesModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="addressesModalLabel">Adresler</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body" id="divAddresses">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary me-auto" data-bs-toggle="modal" onclick="NewAddress()">
                        Yeni Adres Ekle
                    </button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Address Modal -->
    <div class="modal modal-lg fade" id="addressEditModal" tabindex="-1" aria-labelledby="addressEditModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="addressEditModalLabel">Adres Bilgileri</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <label for="inputAddressName" class="form-label">Adres Adı</label>
                    <input type="text" id="inputAddressName" class="form-control">

                    <label for="inputDescription" class="form-label">Adres Açıklaması</label>
                    <input type="text" id="inputDescription" class="form-control">

                    <label for="selectCity" class="form-label">Şehir</label>
                    <select type="text" id="selectCity" class="form-select"></select>

                    <label for="selectDistrict" class="form-label">İlçe</label>
                    <select type="text" id="selectDistrict" class="form-select"></select>

                    <label for="selectCountry" class="form-label">Ülke</label>
                    <select type="text" id="selectCountry" class="form-select"></select>

                    <label for="inputZipCode" class="form-label">Posta Kodu</label>
                    <input type="text" id="inputZipCode" class="form-control">


                    <div class="form-check mt-2">
                        <input class="form-check-input checked" type="checkbox" value="" id="inputActive">
                        <label class="form-check-label" for="inputActive">
                            Aktif
                        </label>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Vazgeç</button>
                    <button type="button" class="btn btn-primary" onclick="SaveAddress()">Kaydet</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Service Modal -->
    <div class="modal modal-xl fade" id="servicesModal" tabindex="-1" aria-labelledby="addressesModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="serviceModalLabel">Servisler</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>

                <div class="modal-body" id="divServices">
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-primary me-auto" data-bs-toggle="modal" onclick="NewService()">
                        Servis Gir
                    </button>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Kapat</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Service Modal -->
    <div class="modal modal-lg fade" id="serviceEditModal" tabindex="-1" aria-labelledby="serviceEditModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="serviceEditModalLabel">Servis Bilgileri</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <label for="inputServiceCustomerName" class="form-label">Müşteri Adı</label>
                    <input class="form-control" type="text" id="inputServiceCustomerName" value="Müşteri Adı" disabled readonly>

                    <label for="selectProcessType" class="form-label">İşlem Türü</label>
                    <select type="text" id="selectProcessType" class="form-select"></select>

                    <label for="selectServiceProduct" class="form-label">Ürün</label>
                    <select type="text" id="selectServiceProduct" class="form-select"></select>

                    <label for="inputItemDescription" class="form-label">Parça Açıklaması</label>
                    <input type="text" id="inputItemDescription" class="form-control">

                    <label for="inputCustomerComplaint" class="form-label">Müşteri Şikayeti</label>
                    <input type="text" id="inputCustomerComplaint" class="form-control">

                    <label for="inputWaterValues" class="form-label">Su Değerleri</label>
                    <input type="text" id="inputWaterValues" class="form-control">

                    <label for="selectServicePersonnel" class="form-label">Servis Personeli</label>
                    <select type="text" id="selectServicePersonnel" class="form-select"></select>

                    <div class="input-group mt-3">
                        <span class="input-group-text">Özel Not</span>
                        <textarea class="form-control" id="inputSpecialNote2" aria-label="Özel Not"></textarea>
                    </div>


                    <div class="form-check mt-2">
                        <input class="form-check-input checked" type="checkbox" value="" id="inputIsMaintenanceDone">
                        <label class="form-check-label" for="inputIsMaintenanceDone">
                            Bakım Yapıldı mı?
                        </label>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Vazgeç</button>
                    <button type="button" class="btn btn-primary" onclick="SaveService()">Kaydet</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Edit Modal -->
    <div class="modal modal-lg fade" id="customerModal" tabindex="-1" aria-labelledby="customerModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="customerModalLabel">Müşteri Bilgileri</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">

                    <label for="inputCustomerName" class="form-label">Müşteri Adı</label>
                    <input type="text" id="inputCustomerName" class="form-control">

                    <label for="inputPhone" class="form-label">Telefon</label>
                    <input type="text" id="inputPhone" class="form-control"></input>

                    <label for="inputHomePhone" class="form-label">Ev Telefon</label>
                    <input type="text" id="inputHomePhone" class="form-control"></input>

                    <label for="selectSalesperson" class="form-label">Satış Personeli</label>
                    <select type="text" id="selectSalesperson" class="form-select"></select>

                    <label for="selectProduct" class="form-label">Ürün</label>
                    <select type="text" id="selectProduct" class="form-select"></select>


                    <div class="form-check mt-2">
                        <input class="form-check-input checked" type="checkbox" value="" id="inputActive">
                        <label class="form-check-label" for="inputActive">
                            Aktif
                        </label>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Vazgeç</button>
                    <button type="button" class="btn btn-primary" onclick="SaveCustomer()">Kaydet</button>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

Takip.Web/Areas/Admin/Views/Home/Role.cshtml
<script type="text/javascript" src="~/js/admin/role.js" asp-append-version="true"></script>
<div class="row">
    <div class="p-3 col-12">
        <div>
            <div class="d-inline-flex mt-5 text-center">
                <div>
                    <label for="inputSearch1" class="form-label mt-3 me-3">ID'ye göre</label>
                    <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch1" onkeyup='tableSearch(0,"inputSearch1","roleTable")'>
                </div>
                <div>
                    <label for="inputSearch2" class="form-label mt-3 me-3">Rol ismine göre</label>
                    <input class="form-control me-3" style="max-width: 150px" type="search" placeholder="" id="inputSearch2" onkeyup='tableSearch(1,"inputSearch2","roleTable")'>
                </div>
            </div>
        </div>



        <div id="divRoles" class="mt-2">
        </div>

        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" onclick="NewRole()">
            Yeni Rol Ekle
        </button>

        <!-- Modal -->
        <div class="modal fade" id="roleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">Rol Bilgileri</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">

                        <label for="inputRoleName" class="form-label">Rol Adı</label>
                        <input type="text" id="inputRoleName" class="form-control">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Vazgeç</button>
                        <button type="button" class="btn btn-primary" onclick="SaveRole()">Kaydet</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Takip.Web/Views/Shared/_AdminLayout.cshtml
@using Takip.Web.Code;
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Takip.Web</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>src = "https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"</script>

    <script>
        let TOKEN = "@Repo.Session.Token";
    </script>


    <link rel="stylesheet" href="~/lib/bootstrap/main.css" />
    <link rel="stylesheet" href="~/css/adminlayout.css" asp-append-version="true" />
    <!-- <link rel="stylesheet" href="~/Takip.Web.styles.css" asp-append-version="true" /> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />

</head>

<body>
    <header>
        <nav class="navbar bg-body-tertiary fixed-top">
            <div class="container">
                <a class="navbar-brand fw-bold text-light me-auto" id="title" asp-area="Admin" asp-controller="Home" asp-action="Index">KARTANESİ TAKİP SİSTEMİ</a>

                @if (string.IsNullOrEmpty(Repo.Session.Email))
                {
                    <a class="me-3 text-light" asp-area="" asp-controller="Account" asp-action="Login">Giriş Yapın</a>
                }
                else
                {
                    <a class="me-3 bg-primary text-light text-decoration-none rounded" asp-area="Admin" asp-controller="Personnel" asp-action="AccountDetails"><span class="m-3">@Repo.Session.Name</span></a>
                    <a class="me-3 bg-danger text-light text-decoration-none  rounded" asp-area="" asp-controller="Account" asp-action="Logout"><span class="m-3">Çıkış Yap</span></a>

                }

                <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header background-color-ozel">
                        <h5 class="offcanvas-title text-light" id="offcanvasNavbarLabel">Menü</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <li class="nav-item">
                                <a class="nav-link active fs-5 fw-bold" aria-current="page" asp-area="Admin" asp-controller="Home" asp-action="Index">
                                    <i class="bi bi-house-fill me-2"></i>Ana Sayfa
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active fs-5 fw-bold" aria-current="page" asp-area="Admin" asp-controller="Home" asp-action="Customer">
                                    <i class="bi bi-person-circle me-2"></i>Müşteriler
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active fs-5 fw-bold" aria-current="page" asp-area="Admin" asp-controller="Home" asp-action="Service">
                                    <i class="bi bi-wrench-adjustable me-2"></i>Servis
                                </a>
                            </li>
                            @if (Repo.Session.Role == "Admin")
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle fs-5 fw-bold" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="bi bi-pencil-fill me-2"></i>
                                        Admin Menüsü
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Personnel">Personeller</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li>
                                            <a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Product">Ürün Düzenle</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li>
                                            <a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Role">Rol Düzenle</a>
                                        </li>
                                        <li>
                                            <hr class="dropdown-divider">
                                        </li>
                                        <li>
                                            <a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Category">Kategori Düzenle</a>
                                        </li>



                                    </ul>
                                </li>
                            }

                        </ul>
                        <form class="d-flex mt-3" role="search">
                            <input class="form-control me-2" type="search" placeholder="Arama" aria-label="Search">
                            <button class="btn btn-outline-primary" type="submit"><i class="bi bi-search-heart"></i></button>
                        </form>
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">

        @RenderBody()


    </div>

    <footer class="border-top footer text-muted" id="footerBottom">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-sm-6 mt-2">
                    <div class="single-box">
                        <img class="img-fluid" src="~/img/logo.jpg" />

                    </div>
                </div>

                <div class="col-lg-3 col-sm-6 mt-2">
                    <div class="single-box">
                        <p class="text-center">Kartanesi Takip Sistemi Ahlatçı yazılım kursu projesi için hazırlanmıştır. Henüz bitmemiş olup, mevcut fonksiyonları çalışmaktadır.</p>
                        <h5 class="text-center text-secondary fw-bold">Mehmet Çağrı Şahinci</h5>
                    </div>
                </div>

                <div class="col-lg-3 col-sm-6 mt-2">
                    <div class="single-box">
                        <h5 class="text-secondary fw-bold">Menü</h5>
                        <ul>
                            <li><a asp-area="Admin" asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>
                            <li><a asp-area="Admin" asp-controller="Home" asp-action="Customer">Müşteriler</a></li>
                            <li><a asp-area="Admin" asp-controller="Home" asp-action="Service">Servis</a></li>
                        </ul>
                    </div>
                </div>

                @if (Repo.Session.Role == "Admin")
                {
                    <div class="col-lg-3 col-sm-6 mt-2">
                        <div class="single-box">
                            <h5 class="text-secondary fw-bold">Admin Menüsü</h5>
                            <ul>
                                <li><a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Personnel">Personeller</a></li>
                                <li><a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Product">Ürün Düzenle</a></li>
                                <li><a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Role">Rol Düzenle</a></li>
                                <li><a class="nav-link text-dark ms-3" asp-area="Admin" asp-controller="Home" asp-action="Category">Kategori Düzenle</a></li>
                            </ul>
                        </div>
                    </div>
                }
                else
                {
                    <div class="col-lg-3 col-sm-6 mt-2">
                        <div class="single-box">
                            <h5 class="text-secondary fw-bold">Footer Menüleri</h5>
                            <ul>
                                <li><a href="">Dolu Gözüksün</a></li>
                                <li><a href="">Diye Koyduğum</a></li>
                                <li><a href="">Menüler</a></li>
                            </ul>
                        </div>
                    </div>
                }


            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>